version: '2'
services:

  flask-example:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/flask-example
    user: root
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
      - SQL_SERVER=videofaces-mysql
      - GRPC_SERVER=videofaces-grpc
      - GRPC_SERVER_PORT=50051
      - BACKEND_REST=backend-rest

